#spring.application.name=backend
server:
  port: 8080
  servlet:
    #context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ct240_pm_db"
    username: root
    password: root
  # ?? ch??ng trình t? t?o b?ng
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

